quasar:
  satellites:
    -
      name: Kenobi
      position:
        x: -500
        y: -20
    -
      name: Skywalker
      position:
        x: 100
        y: -100
    -
      name: Sato
      position:
        x: 500
        y: 100